version: '3.8'

services:
  app:
    image: golang:1.23rc1
    container_name: todo-app
    volumes:
      - .:/go/src/pet-project
    working_dir: /go/src/pet-project
    command: go run cmd/main.go
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: todo-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database", "postgres://user:password@db:5432/todo?sslmode=disable", "up" ]
    volumes:
      - ./migrations:/migrations
      - ./wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - db
    entrypoint: [ "sh", "-c", "sleep 1 && /migrate -path /migrations -database postgres://user:password@db:5432/todo?sslmode=disable up" ]

volumes:
  db_data: